### ISSUE TITLE
zfs-replicate can't send snapshot after creating a new FS

### ISSUE THREAD

**Issue by gdevenyi** [aaronhurt/zfs-replicate#13]
I'm replicating a full pool with zfs-replicate.

I created a new fs on my master pool, now zfs-replicate log shows (on first run)

```
cannot mount '/data/microscopestorage': failed to create mountpoint
```

After subsequent runs now it complains:

```
cannot receive new filesystem stream: destination has snapshots (eg. data/microscopestorage@zfs-auto-snap_daily-2015-11-25-1156)
must destroy them to overwrite it
```

How do I fix this?

**Comment by tschettervictor** [comment]
https://github.com/tschettervictor/zfs-replicate

Check out my fork

**Comment by aaronhurt** [comment]
Don't promote.

**Comment by tschettervictor** [comment]
Removed. My apologies.
