### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by UralZima** [aaronhurt/zfs-replicate#15]
Hello. Thanks for your script. 
I think, you need to add to the documentation some points:
* Dest datapools must exist. 
* if I want to backup rpool/ROOT to bkpool/work/ROOT, bkpool/work and bkpool/work/ROOT must exist, but in config it will be rpool/ROOT:bkpool/work, not rpool/ROOT:bkpool/work/ROOT as I tried and failed

And question:
I use zfsnap to create and keep local snapshots. If I delete snapshots locally, will they be removed on next sync on backup in this scenario: rpool/ROOT:bkpool/work ? Do I need to do any cleanup on bkpool?

Thanks

**Comment by tschettervictor** [comment]
See my fork here

https://github.com/tschettervictor/zfs-replicate

**Comment by tschettervictor** [comment]
Removed. My apologies.
