### ISSUE TITLE
Solaris non posix date

### ISSUE THREAD

**Issue by daroga0002** [aaronhurt/zfs-replicate#16]
Solaris 10 date command is POSIX compliant and doesn`t implement
 ```
date "+%s"
```
so in config.sh it can be replaced by 
```
perl -e 'print time."\n";'
```

Line:
https://github.com/leprechau/zfs-replicate/blob/17bf8fb57b51560b30abfae7f23aa19f1e8f9e4c/config.sample.sh#L78

**Comment by aaronhurt** [comment]
This was never tested on Solaris, it was only ever tested on FreeBSD and Linux.
