### ISSUE TITLE
question

### ISSUE THREAD

**Issue by killmasta93** [aaronhurt/zfs-replicate#17]
Hi,
So if i understood correctly i would configure the config..sh, then run ./zfs-replicate.sh but what im getting is this 
`root@prometheus2:~/zfs-replicate# ./zfs-replicate.sh 
Sourcing configuration from config.sh
`
this is my config 
https://pastebin.com/mzSj3KgM

**Comment by tschettervictor** [comment]
See my fork here

https://github.com/tschettervictor/zfs-replicate

**Comment by aaronhurt** [comment]
Don't promote.

**Comment by tschettervictor** [comment]
Removed. My apologies.
