### ISSUE TITLE
No updates in 8 years + Solution

### ISSUE THREAD

**Issue by tschettervictor** [aaronhurt/zfs-replicate#18]
Since there have been no updates to this project in 8 years, I have forged it and enhanced the script to inside features such as

- push or pull replication
- better error checking
- status report script to check status of latest run

If anyone is interested, here is my fork 

https://github.com/tschettervictor/zfs-replicate

**Comment by aaronhurt** [comment]
It's poor form to advertise in someone else's repo. You didn't even try a pull request.

**Comment by tschettervictor** [comment]
I apologize. I assumed this was a dead project.
Forgive me if I overstepped. 

Would you accept a PR?

**Comment by tschettervictor** [comment]
Will get it submittted. Again, I’m terribly sorry.

**Comment by aaronhurt** [comment]
No worries, it's definitely an old project, but it still works for my personal purposes. Happy to entertain PRs though.

**Comment by tschettervictor** [comment]
Pushed. You might make some changes such as the file revision ID, but I otherwise thouroly tested the script with all combinations of PUSH, PULL, REMOTE, LOCAL, RECURSE_CHILDREN and ALLOW_REPLICATE_FROM_SCRATCH.

I did each test by first running the script 3 times to make sure all was good with initial and incremental replication, the deleted snapshots from one side, and ran it again. Then I restarted from scratch and deleted snapshots from the other side, and ran it again. I did this with each of the combinations listed above. The only thing I didn't test was the ALLOW_ROOT_DATASETS option.

With each of the combinations above I got the result that the combinations were looking for. IE- if ALLOW_REPLICATE_FROM_SCRATCH was set, it wouldn't care about existing data or snapshots, it would delete them on whichever side was the source and start over. If it was not set, it would exit_error and print FAILED message.

Look it over and let me know what you think.

**Comment by tschettervictor** [comment]
Will the new version show up in FreeBSD pkg repo?

I renamed my private fork to xigmanas-zfs-replicate as that is an appliance OS and it isn’t standard procedure to download pkgs to it.

**Comment by tschettervictor** [comment]
> Will the new version show up in FreeBSD pkg repo?
> 
> I renamed my private fork to xigmanas-zfs-replicate as that is an appliance OS and it isn’t standard procedure to download pkgs to it.

Just bumping this question.

**Comment by aaronhurt** [comment]
I'm not sure, I don't maintain that package. I can however reach out and see if the maintainer can publish an update.

For reference, this is the package in the official FreeBSD package repo: https://www.freshports.org/sysutils/zfs-replicate/

**Comment by aaronhurt** [comment]
Doing a bit of Googling it appears it's also made it into a few blog posts in the ~ 13 years since I first uploaded this script to GitHub 😄

**Comment by tschettervictor** [comment]
That is fine. And yes it is used by some folks...

I tried to message the maintainer email, but got a "Couldn't deliver" error.
